[project]
name = "pyssistown-server"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "sqlmodel",
    "alembic",
]

[project.optional-dependencies]
development = [
    "pytest",
]

[tool.uvicorn]
factory = true
